"""Explicit order state machine. Transitions are validated here; the API/UI can
never set an order state directly, it can only request a transition."""

# Main happy-path flow
CREATED = "CREATED"
PRICED = "PRICED"
SEARCHING_PROVIDER = "SEARCHING_PROVIDER"
PROVIDER_ASSIGNED = "PROVIDER_ASSIGNED"
PROVIDER_ACCEPTED = "PROVIDER_ACCEPTED"
PROVIDER_EN_ROUTE = "PROVIDER_EN_ROUTE"
SERVICE_STARTED = "SERVICE_STARTED"
SERVICE_COMPLETED = "SERVICE_COMPLETED"
PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED"
PAYOUT_PENDING = "PAYOUT_PENDING"
COMPLETED = "COMPLETED"

# Alternative states
CANCELLED = "CANCELLED"
EXPIRED = "EXPIRED"
PAYMENT_FAILED = "PAYMENT_FAILED"
NO_PROVIDER_FOUND = "NO_PROVIDER_FOUND"
DISPUTED = "DISPUTED"

TRANSITIONS: dict[str, set[str]] = {
    CREATED: {PRICED, CANCELLED},
    PRICED: {SEARCHING_PROVIDER, CANCELLED},
    SEARCHING_PROVIDER: {PROVIDER_ASSIGNED, NO_PROVIDER_FOUND, CANCELLED, EXPIRED},
    PROVIDER_ASSIGNED: {PROVIDER_ACCEPTED, SEARCHING_PROVIDER, CANCELLED, EXPIRED},
    PROVIDER_ACCEPTED: {PROVIDER_EN_ROUTE, CANCELLED},
    PROVIDER_EN_ROUTE: {SERVICE_STARTED, CANCELLED},
    SERVICE_STARTED: {SERVICE_COMPLETED, DISPUTED},
    SERVICE_COMPLETED: {PAYMENT_CONFIRMED, PAYMENT_FAILED, DISPUTED},
    PAYMENT_CONFIRMED: {PAYOUT_PENDING, DISPUTED},
    PAYOUT_PENDING: {COMPLETED},
    COMPLETED: set(),
    CANCELLED: set(),
    EXPIRED: set(),
    PAYMENT_FAILED: {PAYMENT_CONFIRMED, CANCELLED},
    NO_PROVIDER_FOUND: {SEARCHING_PROVIDER, CANCELLED},
    DISPUTED: {COMPLETED, CANCELLED},
}

# States where the customer is still allowed to cancel
CUSTOMER_CANCELLABLE = {
    CREATED, PRICED, SEARCHING_PROVIDER, PROVIDER_ASSIGNED,
    PROVIDER_ACCEPTED, PROVIDER_EN_ROUTE, NO_PROVIDER_FOUND,
}


def can_transition(current: str, target: str) -> bool:
    return target in TRANSITIONS.get(current, set())
